### ISSUE TITLE
To support in private network

### ISSUE THREAD

**Issue by susarlanikhilesh** [libp2p/go-libp2p-relay-daemon#16]
With regards to this discussion in the ipfs, I want to work on this to support on private network too. 

https://discuss.ipfs.io/t/hop-cant-speak-relay-error-when-setting-up-ipfs-private-network/13897/7?u=susarlanikhilesh

Can you please guide me on who to start with and what are the changes to be done? 

I looked at the go-ipfs on how they supporting private key by reading the swarm key from the file and adding it to the opts for libp2p. 
Should we even do it in the same way. 

Thank you

**Comment by MarcoPolo** [comment]
Hey @susarlanikhilesh. You'll probably need to add a config option to the config in this repo to accept a pre shared private key. Then you need to use this [option](https://github.com/libp2p/go-libp2p/blob/1c6bfa228579e9c536e3e554ef4548e8ba50db1d/options.go#L153) with the PSK when you construct the libp2p object (with ".New()").

That should be enough to get you started, let me know if you run into any issues.

**Comment by susarlanikhilesh** [comment]
@MarcoPolo can I work on it. I wrote as you mentioned. Probably I can raise a PR.
Thank you.
