### ISSUE TITLE
Prometheus metrics in config

### ISSUE THREAD

**Issue by mohammad-babaei** [libp2p/go-libp2p-relay-daemon#41]
There should be the ability to enable and disable prometheus metrics in the config

**Comment by marten-seemann** [comment]
Feel free to raise a PR.

**Comment by mohammad-babaei** [comment]
I added metrics, enabled DHT(server mode) and bumped the libp2p library version in  this [PR](https://github.com/libp2p/go-libp2p-relay-daemon/pull/42)
